### ISSUE TITLE
invalid literal for int()

### ISSUE THREAD

**Issue by sabinechen** [JasonFengGit/Naive-Bayes-Number-Recognition#1]
I am a new pythoner,when i run the code ,it report the error “ValueError: invalid literal for int() with base 10: 'label'” in line 1"train_data = [list(map(int, line.strip().split(","))) for line in open("mnist_train.csv").read().strip().split("\n")]",it is hard for me to figure it out

**Comment by JasonFengGit** [comment]
Sorry for the late response. If you look into the data, the CSV file contains a "label 1x1 1x3 ..." row. Simply removing it would work. Thanks for reaching out!
